### ISSUE TITLE
may you share data  made-ml-2019-hw1

### ISSUE THREAD

**Issue by Sandy4321** [SerSmith/MADE-machine-learning#1]
may you share data
from
https://www.kaggle.com/c/made-ml-2019-hw1/data

**Comment by SerSmith** [comment]
Yeap, here you are.

[made-ml-2019-hw1.zip](https://github.com/SerSmith/MADE-machine-learning/files/7604041/made-ml-2019-hw1.zip)

**Comment by Sandy4321** [comment]
great thanks

do you have more code examples for vowpalwabbit?
